clear;
close all;

% Load spectral data generated by script uLoggerSpectraGenScript.m
load('\...\UNICEFsmartHandpumpConditionMonitoring\dataPlots\spectraLoc1Acc3FftN128Freq3_3_60dB.mat');

myOptions.debug = false;
myOptions.balanceData = true;
myTrainFun = @uLoggerRecordingsClassifyLrTrain;
myTestFun = @uLoggerRecordingsClassifyLrTest;

% Note, may need to re-run to allow both validation groups to have examples
% from two classes!!
[yOut, xValTrainedClassifier, crossValKeysByGroup] = uNValByGroup(dataset,2,myTrainFun,myTestFun,myOptions);

% ROC
figure(10);
[Pfa,Pd,~,auc] = prtScoreRoc(yOut,dataset.labels);
plot(Pfa,Pd,'LineWidth',2);
hold on;tempVec = (0:.01:1)';plot(tempVec,tempVec,':k');hold off;
title('2-fold xVal ROC Performance for Pump Location 1');
xlabel('Pfp');ylabel('Ptp');


